### ISSUE TITLE
ng2-typeahead.js not found

### ISSUE THREAD

**Issue by DIneshArun1991** [brinkmanjg/ng2-typeahead#34]
Hi,

I have complied after configuration changes also. still getting the below error

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3001/node_modules/ng2-typeahead/ng2-typeahead.js
	Error: XHR error (404 Not Found) loading http://localhost:3001/node_modules/ng2-typeahead/ng2-typeahead.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.js:1199:29) [<root>]
	    at Zone.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.js:165:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3001/node_modules/ng2-typeahead/ng2-typeahead.js as "ng2-typeahead" from http://localhost:3001/app/app.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3001/node_modules/zone.js/dist/zone.js:1199:29) [<root>]
	    at Zone.runTask (http://localhost:3001/node_modules/zone.js/dist/zone.js:165:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3001/node_modules/zone.js/dist/zone.js:460:38) [<root>]
	Error loading http://localhost:3001/node_modules/ng2-typeahead/ng2-typeahead.js as "ng2-typeahead" from http://localhost:3001/app/app.module.js

**Comment by Seville** [comment]
Well what solved this issue for me was in systemjs.config.js, under map object I changed the recommended 'ng2-typeahead': 'node_modules/ng2-typeahead',  to 'ng2-typeahead': 'node_modules/ng2-typeahead/lib',
