### ISSUE TITLE
Can't bind to 'ngModel' since it isn't a known property of 'typeahead'.

### ISSUE THREAD

**Issue by suranan** [brinkmanjg/ng2-typeahead#41]
Hi,

I have complied after configuration changes also. still getting the below error

Uncaught Error: Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'typeahead'. ("<typeahead [ERROR ->][(ngModel)]="selectedFruit" [list]="fruits" [searchProperty]="'searchText'" [displayProperty]="'name'"): ng:///LoginFormModule/LoginFormComponent.html@0:11
Can't bind to 'list' since it isn't a known property of 'typeahead'. ("<typeahead [(ngModel)]="selectedFruit" [ERROR ->][list]="fruits" [searchProperty]="'searchText'" [displayProperty]="'name'" [maxSuggestions]="2" (sugg"): ng:///LoginFormModule/LoginFormComponent.html@0:39
Can't bind to 'searchProperty' since it isn't a known property of 'typeahead'. ("<typeahead [(ngModel)]="selectedFruit" [list]="fruits" [ERROR ->][searchProperty]="'searchText'" [displayProperty]="'name'" [maxSuggestions]="2" (suggestionSelected)="): ng:///LoginFormModule/LoginFormComponent.html@0:55
Can't bind to 'displayProperty' since it isn't a known property of 'typeahead'. ("<typeahead [(ngModel)]="selectedFruit" [list]="fruits" [searchProperty]="'searchText'" [ERROR ->][displayProperty]="'name'" [maxSuggestions]="2" (suggestionSelected)="fruitSelected($event)" placehol"): ng:///LoginFormModule/LoginFormComponent.html@0:87
Can't bind to 'maxSuggestions' since it isn't a known property of 'typeahead'. ("gModel)]="selectedFruit" [list]="fruits" [searchProperty]="'searchText'" [displayProperty]="'name'" [ERROR ->][maxSuggestions]="2" (suggestionSelected)="fruitSelected($event)" placeholder="Begin typing a fruit">"): ng:///LoginFormModule/LoginFormComponent.html@0:114
'typeahead' is not a known element:
1. If 'typeahead' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("[ERROR ->]<typeahead [(ngModel)]="selectedFruit" [list]="fruits" [searchProperty]="'searchText'" [displayProper"): ng:///LoginFormModule/LoginFormComponent.html@0:0
    at syntaxError (http://localhost:4200/vendor.bundle.js:46254:34)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:57374:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:71526:39)
    at http://localhost:4200/vendor.bundle.js:71446:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:71446:19)
    at http://localhost:4200/vendor.bundle.js:71333:19
    at Object.then (http://localhost:4200/vendor.bundle.js:46243:148)
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:71332:26)
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:71261:37)

app.module.ts 

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppRoutingModule } from './app-routing.module';

import { AppComponent } from './app.component';

import { LoginModule } from './login';

import { Typeahead } from 'ng2-typeahead';

@NgModule({  
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule,
    LoginModule
  ],
  declarations: [
    AppComponent,
    Typeahead
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by shayanpaul91** [comment]
I am facing the same issue.. Are you able to solve this issue.. If so please share how you have solve the issue
